### ISSUE TITLE
`toBeVisible` does not exist on type

### ISSUE THREAD

**Issue by developer239** [solkaz/ts-detox-example#6]
Does anyone have any idea how to fix this? 🙏 

![image](https://user-images.githubusercontent.com/14946081/74094467-0bd82380-4ae2-11ea-9a07-24fbd6a6a9ee.png)

**Comment by latusdenis** [comment]
@developer239 `import { by, expect, element } from 'detox';`

**Comment by developer239** [comment]
I know but it would be nice to overwrite jest types somehow. 🙂
